import-repo repoName:
  #!/usr/bin/env bash
  go run main.go import {{repoName}}
  IFS='/' read -r owner repo <<< {{repoName}}
  mkdir -p "../../feature/github-repo-provisioning/importer_tmp_dir/$owner/"
  cp "configs/$owner/$repo.yaml" "../../feature/github-repo-provisioning/importer_tmp_dir/$owner/"

import-repos:
  go run main.go bulk-import -c import-config.yaml
  mkdir -p "../../feature/github-repo-provisioning/importer_tmp_dir/$OWNER/"
  find configs/"$OWNER" -maxdepth 1 -type f \( -name "*.yaml" -o -name ".*.yaml" \) -print -exec cp {} "../../feature/github-repo-provisioning/importer_tmp_dir/$OWNER/" \;

test:
  go test ./...

compare dirA dirB:
  go run main.go compare {{dirA}} {{dirB}}