name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  echo:
    name: "Echo"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo
        run: echo "hello world"