name: "Terraform Cloud Drift Check"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  drift-check:
    name: "Drift Check (${{ matrix.environment }})"
    runs-on: ubuntu-latest
    environment: schedule-${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment: ["dev", "prod"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Terraform Cloud drift check
        id: drift
        uses: ./.github/actions/drift-detector
        with:
          tfc-token: ${{ secrets.TFC_TOKEN }}
          workspace-id: ${{ vars.WORKSPACE_ID }}
          polling-interval: 30
          max-poll-attempts: 10

      - name: Notify about drift via Slack
#        if: ${{ steps.drift.outputs.drift == 'true' }}
        run: echo "Has drift ${{ steps.drift.outputs.drift }}"