name: "Terraform Cloud Drift Check"

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 * * * *'

jobs:
  drift-check:
    name: "Drift Check"
    runs-on: ubuntu-latest
    environment: schedule-${{ matrix.environment }}-${{ matrix.owner }}
    strategy:
      fail-fast: false
      matrix:
        environment: ["prod"]
        owner: ["G-Research", "armadaproject"]
        include:
          - environment: "dev"
            owner: "gr-oss-devops"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Terraform Cloud drift check
        id: drift
        uses: ./.github/actions/drift-detector
        with:
          tfc-token: ${{ secrets.TFC_TOKEN }}
          workspace-id: ${{ vars.WORKSPACE_ID }}
          polling-interval: 30

      - name: Inspect drift
        run: |
          if [[ "${{ steps.drift.outputs.drift }}" == "true" ]]; then
            echo "Drift detected!"
            exit 1
          else
            echo "No drift detected."
          fi