name: Import repo pipeline

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'The name of the repository to import'
        required: true
      owner:
        type: choice
        description: 'The owner of the repository to import'
        options:
          - "G-Research"
          - "armadaproject"
          - "gr-oss-devops"

jobs:
  import-repo:
    runs-on: ubuntu-latest
    name: Import repository
    environment: import-${{ github.ref_name }}-${{ github.event.inputs.owner }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Just
        uses: extractions/setup-just@v2
        with:
          just-version: '1.4.0'

      - name: Generate a token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.event.inputs.owner }}

      - name: Setup vars
        id: setup-vars
        run: |
          echo "full_repo_name=${{ github.event.inputs.owner }}/${{ github.event.inputs.repo_name }}" >> $GITHUB_OUTPUT
          echo "automation_branch_name=import/${{ github.ref_name }}/${{ github.event.inputs.owner }}/${{ github.event.inputs.repo_name }}" >> $GITHUB_OUTPUT 

      - name: Import repo
        working-directory: feature/github-repo-importer
        run: just import-repo ${{ steps.setup-vars.outputs.full_repo_name }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Handle configuration files
        uses: ./.github/actions/compare
        with:
          working-directory: feature/github-repo-importer
          source-directory: "../github-repo-provisioning/importer_tmp_dir/"
          target-directory: "../github-repo-provisioning/repo_configs/${{ github.ref_name }}/${{ github.event.inputs.owner }}"

      - name: Create Pull Request
        uses: ./.github/actions/pr-bot
        with:
          branch-name: ${{ steps.setup-vars.outputs.automation_branch_name }}
          pr-title: "Import ${{ github.ref_name }}/${{ steps.setup-vars.outputs.full_repo_name }}"
          commit-message: "Auto-generated changes. Import ${{ github.ref_name }}/${{ steps.setup-vars.outputs.full_repo_name }} repository"
          github-token: ${{ secrets.GITHUB_TOKEN }}