name: Promote Imported Configs

on:
  workflow_dispatch:
    inputs:
      owner:
        type: choice
        description: 'Owner of the repository'
        options:
          - "G-Research"
          - "armadaproject"
          - "gr-oss-devops"
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: ${{ github.event.inputs.owner }}