name: Promote Imported Configs

on:
  workflow_dispatch:
    inputs:
      owner:
        type: choice
        description: 'Owner of the repository'
        options:
          - "G-Research"
          - "armadaproject"
          - "gr-oss-devops"
jobs:
  promote:
    runs-on: ubuntu-latest
    environment: promote-${{ github.ref_name }}-${{ github.event.inputs.owner }}
    steps:
      - name: Debug
        run: echo "${{ github.event.inputs.owner }}"

      - name: Echo message
        run: echo "${{ vars.MESSAGE }}"