name: Promote Imported Configs

on:
  pull_request:
    types: [closed]
    branches: [ prod, dev ]
    paths:
      - 'feature/github-repo-provisioning/importer_tmp_dir/**'

jobs:
  promote:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo ${{ toJson(github) }}